namespace DatabaseAuditor.Reporting.Excel;

using ClosedXML.Excel;
using DatabaseAuditor.Domain.Interfaces;
using DatabaseAuditor.Domain.ValueObjects;
using DatabaseAuditor.Reporting.Models;
using Serilog;

public class ExcelReportGenerator : IReportService
{
    // Brand Colors
    private static readonly XLColor HeaderBg = XLColor.FromHtml("#1E3A5F");
    private static readonly XLColor HeaderFg = XLColor.White;
    private static readonly XLColor AddedBg = XLColor.FromHtml("#E8F5E9");
    private static readonly XLColor AddedFg = XLColor.FromHtml("#2E7D32");
    private static readonly XLColor DeletedBg = XLColor.FromHtml("#FFEBEE");
    private static readonly XLColor DeletedFg = XLColor.FromHtml("#C62828");
    private static readonly XLColor ModifiedBg = XLColor.FromHtml("#FFF8E1");
    private static readonly XLColor ModifiedFg = XLColor.FromHtml("#F57F17");
    private static readonly XLColor SummaryBg = XLColor.FromHtml("#E3F2FD");
    private static readonly XLColor TitleBg = XLColor.FromHtml("#0D47A1");
    private static readonly XLColor AlternateRow = XLColor.FromHtml("#F5F5F5");

    public async Task<string> GenerateExcelAsync(
        CompareSession session,
        string outputPath,
        CancellationToken cancellationToken = default)
    {
        var sw = System.Diagnostics.Stopwatch.StartNew();

        try
        {
            var model = ReportModel.FromSession(session);

            await Task.Run(() =>
            {
                using var workbook = new XLWorkbook();

                if (model.CompareType == Domain.Enums.CompareType.Procedure)
                {
                    BuildProcedureParameterComparisonSheet(workbook, model);
                }
                else
                {
                    BuildSummarySheet(workbook, model);
                    BuildResultSheet(workbook, model, "Added",
                        model.AddedObjects, AddedBg, AddedFg);
                    BuildResultSheet(workbook, model, "Deleted",
                        model.DeletedObjects, DeletedBg, DeletedFg);
                    BuildModifiedSheet(workbook, model);
                    BuildAllResultsSheet(workbook, model);
                }

                workbook.SaveAs(outputPath);
            }, cancellationToken);

            sw.Stop();
            Log.Information("[Excel] Report generated at {Path} in {Ms}ms",
                outputPath, sw.ElapsedMilliseconds);

            return outputPath;
        }
        catch (Exception ex)
        {
            Log.Error(ex, "[Excel] Failed to generate report at {Path}", outputPath);
            throw;
        }
    }

    public Task<string> GeneratePdfAsync(
        CompareSession session,
        string outputPath,
        CancellationToken cancellationToken = default)
        => throw new NotSupportedException("Use PdfReportGenerator for PDF output.");

    // -------------------------------------------------------------------------
    // Summary Sheet
    // -------------------------------------------------------------------------
    private static void BuildSummarySheet(XLWorkbook wb, ReportModel model)
    {
        var ws = wb.Worksheets.Add("Summary");
        ws.ShowGridLines = false;

        // Title Block
        MergeCells(ws, 1, 1, 2, 6);
        var title = ws.Cell(1, 1);
        title.Value = model.Title;
        title.Style.Font.Bold = true;
        title.Style.Font.FontSize = 20;
        title.Style.Font.FontColor = XLColor.White;
        title.Style.Fill.BackgroundColor = TitleBg;
        title.Style.Alignment.Horizontal = XLAlignmentHorizontalValues.Center;
        title.Style.Alignment.Vertical = XLAlignmentVerticalValues.Center;

        MergeCells(ws, 3, 1, 3, 6);
        var company = ws.Cell(3, 1);
        company.Value = model.CompanyName;
        company.Style.Font.Bold = true;
        company.Style.Font.FontSize = 13;
        company.Style.Font.FontColor = XLColor.FromHtml("#0D47A1");
        company.Style.Alignment.Horizontal = XLAlignmentHorizontalValues.Center;

        // Section: Report Info
        int row = 5;
        WriteSection(ws, ref row, "Report Information");
        WriteRow(ws, ref row, "Generated At", model.GeneratedAt.ToString("yyyy-MM-dd HH:mm:ss"));
        WriteRow(ws, ref row, "Generated By", model.GeneratedBy);
        WriteRow(ws, ref row, "Session ID", model.SessionId.ToString());
        WriteRow(ws, ref row, "Comparison Scope", model.ComparisonScope.ToString());
        WriteRow(ws, ref row, "Compare Type", model.CompareType.ToString());
        WriteRow(ws, ref row, "Status", model.IsSuccess ? "Success" : "Failed");
        WriteRow(ws, ref row, "Execution Time",
            $"{model.ExecutionTime.TotalSeconds:F2} seconds");
        WriteRow(ws, ref row, "Selected Objects",
            model.SelectedObjects.Count == 0 ? "All objects in scope" : string.Join(", ", model.SelectedObjects));

        row++;
        WriteSection(ws, ref row, "Source Environment");
        WriteRow(ws, ref row, "Environment", model.SourceEnvironment);
        WriteRow(ws, ref row, "Database Type", model.SourceDatabaseType.ToString());
        WriteRow(ws, ref row, "Server", model.SourceServer);
        WriteRow(ws, ref row, "Database", model.SourceDatabase);

        row++;
        WriteSection(ws, ref row, "Target Environment");
        WriteRow(ws, ref row, "Environment", model.TargetEnvironment);
        WriteRow(ws, ref row, "Database Type", model.TargetDatabaseType.ToString());
        WriteRow(ws, ref row, "Server", model.TargetServer);
        WriteRow(ws, ref row, "Database", model.TargetDatabase);

        row++;
        WriteSection(ws, ref row, "Comparison Summary");

        WriteSummaryCountRow(ws, ref row, "Total Objects", model.TotalObjects, HeaderBg, XLColor.White);
        WriteSummaryCountRow(ws, ref row, "Added Objects", model.AddedCount, AddedBg, AddedFg);
        WriteSummaryCountRow(ws, ref row, "Deleted Objects", model.DeletedCount, DeletedBg, DeletedFg);
        WriteSummaryCountRow(ws, ref row, "Modified Objects", model.ModifiedCount, ModifiedBg, ModifiedFg);
        WriteSummaryCountRow(ws, ref row, "Unchanged Objects", model.UnchangedCount, SummaryBg, XLColor.Black);

        ws.Column(1).Width = 28;
        ws.Column(2).Width = 45;
        ws.Columns(3, 6).Width = 15;
    }

    // -------------------------------------------------------------------------
    // Generic Added/Deleted Sheet
    // -------------------------------------------------------------------------
    private static void BuildResultSheet(
        XLWorkbook wb,
        ReportModel model,
        string sheetName,
        List<Domain.ValueObjects.CompareResult> results,
        XLColor rowBg,
        XLColor rowFg)
    {
        var ws = wb.Worksheets.Add(sheetName);
        ws.ShowGridLines = false;

        WriteSheetTitle(ws, $"{sheetName} Objects — {model.SourceDatabase} vs {model.TargetDatabase}");

        string[] headers = ["#", "Object Type", "Schema", "Object Name", "Change Type", "Detected At"];
        int[] widths = [6, 18, 18, 40, 16, 24];

        WriteHeaders(ws, 3, headers, widths);

        int row = 4;
        int seq = 1;
        foreach (var r in results)
        {
            var isAlt = seq % 2 == 0;
            var bg = isAlt ? AlternateRow : XLColor.White;

            ws.Cell(row, 1).Value = seq++;
            ws.Cell(row, 2).Value = r.ObjectType.ToString();
            ws.Cell(row, 3).Value = r.SchemaName;
            ws.Cell(row, 4).Value = r.ObjectName;
            ws.Cell(row, 5).Value = r.ChangeType.ToString();
            ws.Cell(row, 6).Value = r.DetectedAt.ToString("yyyy-MM-dd HH:mm:ss");

            var rowRange = ws.Range(row, 1, row, 6);
            rowRange.Style.Fill.BackgroundColor = bg;
            rowRange.Style.Font.FontColor = rowFg;
            rowRange.Style.Border.BottomBorder = XLBorderStyleValues.Thin;
            rowRange.Style.Border.BottomBorderColor = XLColor.FromHtml("#E0E0E0");

            ws.Cell(row, 5).Style.Fill.BackgroundColor = rowBg;
            ws.Cell(row, 5).Style.Font.FontColor = rowFg;
            ws.Cell(row, 5).Style.Font.Bold = true;

            row++;
        }

        if (results.Count == 0)
        {
            MergeCells(ws, 4, 1, 4, 6);
            ws.Cell(4, 1).Value = $"No {sheetName.ToLower()} objects found.";
            ws.Cell(4, 1).Style.Font.Italic = true;
            ws.Cell(4, 1).Style.Alignment.Horizontal = XLAlignmentHorizontalValues.Center;
        }

        ApplyWidths(ws, widths);
        ws.SheetView.FreezeRows(3);
    }

    // -------------------------------------------------------------------------
    // Modified Sheet (with differences column)
    // -------------------------------------------------------------------------
    private static void BuildModifiedSheet(XLWorkbook wb, ReportModel model)
    {
        var ws = wb.Worksheets.Add("Modified");
        ws.ShowGridLines = false;

        WriteSheetTitle(ws, $"Modified Objects — {model.SourceDatabase} vs {model.TargetDatabase}");

        string[] headers = ["#", "Object Type", "Schema", "Object Name", "Differences", "Detected At"];
        int[] widths = [6, 18, 18, 35, 60, 24];

        WriteHeaders(ws, 3, headers, widths);

        int row = 4;
        int seq = 1;
        foreach (var r in model.ModifiedObjects)
        {
            var isAlt = seq % 2 == 0;
            var bg = isAlt ? AlternateRow : XLColor.White;

            ws.Cell(row, 1).Value = seq++;
            ws.Cell(row, 2).Value = r.ObjectType.ToString();
            ws.Cell(row, 3).Value = r.SchemaName;
            ws.Cell(row, 4).Value = r.ObjectName;
            ws.Cell(row, 5).Value = string.Join(Environment.NewLine, r.Differences);
            ws.Cell(row, 6).Value = r.DetectedAt.ToString("yyyy-MM-dd HH:mm:ss");

            var rowRange = ws.Range(row, 1, row, 6);
            rowRange.Style.Fill.BackgroundColor = bg;
            rowRange.Style.Border.BottomBorder = XLBorderStyleValues.Thin;
            rowRange.Style.Border.BottomBorderColor = XLColor.FromHtml("#E0E0E0");

            ws.Cell(row, 5).Style.Fill.BackgroundColor = ModifiedBg;
            ws.Cell(row, 5).Style.Font.FontColor = ModifiedFg;
            ws.Cell(row, 5).Style.Alignment.WrapText = true;
            ws.Row(row).Height = Math.Max(20, r.Differences.Count * 15);

            row++;
        }

        if (model.ModifiedObjects.Count == 0)
        {
            MergeCells(ws, 4, 1, 4, 6);
            ws.Cell(4, 1).Value = "No modified objects found.";
            ws.Cell(4, 1).Style.Font.Italic = true;
            ws.Cell(4, 1).Style.Alignment.Horizontal = XLAlignmentHorizontalValues.Center;
        }

        ApplyWidths(ws, widths);
        ws.SheetView.FreezeRows(3);
    }

    // -------------------------------------------------------------------------
    // All Results Sheet
    // -------------------------------------------------------------------------
    private static void BuildAllResultsSheet(XLWorkbook wb, ReportModel model)
    {
        var ws = wb.Worksheets.Add("All Results");
        ws.ShowGridLines = false;

        WriteSheetTitle(ws, $"All Results — {model.SourceDatabase} vs {model.TargetDatabase}");

        string[] headers = ["#", "Object Type", "Schema", "Object Name",
                            "Change Type", "Status", "Source", "Target", "Detected At"];
        int[] widths = [6,   18,             18,       35,
                            16,           16,       30,       30,       24];

        WriteHeaders(ws, 3, headers, widths);

        int row = 4;
        int seq = 1;
        foreach (var r in model.AllResults)
        {
            var isAlt = seq % 2 == 0;

            ws.Cell(row, 1).Value = seq++;
            ws.Cell(row, 2).Value = r.ObjectType.ToString();
            ws.Cell(row, 3).Value = r.SchemaName;
            ws.Cell(row, 4).Value = r.ObjectName;
            ws.Cell(row, 5).Value = r.ChangeType.ToString();
            ws.Cell(row, 6).Value = r.Status.ToString();
            ws.Cell(row, 7).Value = r.SourceValue;
            ws.Cell(row, 8).Value = r.TargetValue;
            ws.Cell(row, 9).Value = r.DetectedAt.ToString("yyyy-MM-dd HH:mm:ss");

            var rowRange = ws.Range(row, 1, row, 9);
            rowRange.Style.Fill.BackgroundColor = isAlt ? AlternateRow : XLColor.White;
            rowRange.Style.Border.BottomBorder = XLBorderStyleValues.Thin;
            rowRange.Style.Border.BottomBorderColor = XLColor.FromHtml("#E0E0E0");

            var changeCell = ws.Cell(row, 5);
            (changeCell.Style.Fill.BackgroundColor, changeCell.Style.Font.FontColor) =
                r.ChangeType switch
                {
                    Domain.Enums.ChangeType.Added => (AddedBg, AddedFg),
                    Domain.Enums.ChangeType.Deleted => (DeletedBg, DeletedFg),
                    Domain.Enums.ChangeType.Modified => (ModifiedBg, ModifiedFg),
                    _ => (XLColor.White, XLColor.Black)
                };
            changeCell.Style.Font.Bold = true;

            row++;
        }

        ApplyWidths(ws, widths);
        ws.SheetView.FreezeRows(3);
    }

    // -------------------------------------------------------------------------
    // Helpers
    // -------------------------------------------------------------------------
    private static void WriteSection(IXLWorksheet ws, ref int row, string title)
    {
        MergeCells(ws, row, 1, row, 6);
        var cell = ws.Cell(row, 1);
        cell.Value = title;
        cell.Style.Font.Bold = true;
        cell.Style.Font.FontSize = 11;
        cell.Style.Font.FontColor = XLColor.White;
        cell.Style.Fill.BackgroundColor = HeaderBg;
        cell.Style.Alignment.Horizontal = XLAlignmentHorizontalValues.Left;
        cell.Style.Alignment.Indent = 1;
        row++;
    }

    private static void WriteRow(IXLWorksheet ws, ref int row, string label, string value)
    {
        ws.Cell(row, 1).Value = label;
        ws.Cell(row, 1).Style.Font.Bold = true;
        ws.Cell(row, 1).Style.Font.FontColor = XLColor.FromHtml("#37474F");
        ws.Cell(row, 2).Value = value;
        ws.Cell(row, 2).Style.Font.FontColor = XLColor.Black;
        ws.Range(row, 1, row, 2).Style.Border.BottomBorder = XLBorderStyleValues.Thin;
        ws.Range(row, 1, row, 2).Style.Border.BottomBorderColor = XLColor.FromHtml("#ECEFF1");
        row++;
    }

    private static void WriteSummaryCountRow(
        IXLWorksheet ws, ref int row,
        string label, int count,
        XLColor bg, XLColor fg)
    {
        MergeCells(ws, row, 1, row, 2);
        ws.Cell(row, 1).Value = label;
        ws.Cell(row, 1).Style.Font.Bold = true;
        ws.Cell(row, 3).Value = count;
        ws.Cell(row, 3).Style.Font.Bold = true;
        ws.Cell(row, 3).Style.Font.FontSize = 13;

        var range = ws.Range(row, 1, row, 6);
        range.Style.Fill.BackgroundColor = bg;
        range.Style.Font.FontColor = fg;
        range.Style.Border.BottomBorder = XLBorderStyleValues.Thin;
        range.Style.Border.BottomBorderColor = XLColor.FromHtml("#E0E0E0");
        row++;
    }

    private static void WriteSheetTitle(IXLWorksheet ws, string title)
    {
        MergeCells(ws, 1, 1, 2, 9);
        var cell = ws.Cell(1, 1);
        cell.Value = title;
        cell.Style.Font.Bold = true;
        cell.Style.Font.FontSize = 14;
        cell.Style.Font.FontColor = XLColor.White;
        cell.Style.Fill.BackgroundColor = TitleBg;
        cell.Style.Alignment.Horizontal = XLAlignmentHorizontalValues.Center;
        cell.Style.Alignment.Vertical = XLAlignmentVerticalValues.Center;
        ws.Row(1).Height = 32;
        ws.Row(2).Height = 10;
    }

    private static void WriteHeaders(
        IXLWorksheet ws, int row,
        string[] headers, int[] widths)
    {
        for (int i = 0; i < headers.Length; i++)
        {
            var cell = ws.Cell(row, i + 1);
            cell.Value = headers[i];
            cell.Style.Font.Bold = true;
            cell.Style.Font.FontColor = HeaderFg;
            cell.Style.Fill.BackgroundColor = HeaderBg;
            cell.Style.Alignment.Horizontal = XLAlignmentHorizontalValues.Center;
            cell.Style.Border.BottomBorder = XLBorderStyleValues.Medium;
            cell.Style.Border.BottomBorderColor = XLColor.FromHtml("#1565C0");
        }
        ws.Row(row).Height = 22;
    }

    private static void ApplyWidths(IXLWorksheet ws, int[] widths)
    {
        for (int i = 0; i < widths.Length; i++)
            ws.Column(i + 1).Width = widths[i];
    }

    private static void MergeCells(
        IXLWorksheet ws,
        int r1, int c1, int r2, int c2)
        => ws.Range(r1, c1, r2, c2).Merge();

    private static void BuildProcedureParameterComparisonSheet(XLWorkbook wb, ReportModel model)
    {
        var ws = wb.Worksheets.Add("Parameter Compare");
        ws.ShowGridLines = false;

        WriteSheetTitle(ws, $"Stored Procedure Parameter Comparison — {model.SourceDatabase} vs {model.TargetDatabase}");

        string[] headers = ["#", "Stored Procedure", "Source Parameter", "Target Parameter", "Difference Details", "Detected At"];
        int[] widths = [6, 30, 35, 35, 45, 20];

        WriteHeaders(ws, 3, headers, widths);

        int row = 4;
        int seq = 1;

        var allProcs = model.ModifiedObjects
            .Concat(model.AddedObjects)
            .Concat(model.DeletedObjects)
            .Where(r => r.ObjectType == Domain.Enums.CompareType.Procedure);

        foreach (var r in allProcs)
        {
            if (r.ChangeType == Domain.Enums.ChangeType.Added)
            {
                var isAlt = seq % 2 == 0;
                var bg = isAlt ? AlternateRow : XLColor.White;

                ws.Cell(row, 1).Value = seq++;
                ws.Cell(row, 2).Value = r.FullObjectName;
                ws.Cell(row, 3).Value = "Missing (Procedure not in Source)";
                ws.Cell(row, 4).Value = "Present in Target";
                ws.Cell(row, 5).Value = "Procedure Added";
                ws.Cell(row, 6).Value = r.DetectedAt.ToString("yyyy-MM-dd HH:mm");

                var rowRange = ws.Range(row, 1, row, 6);
                rowRange.Style.Fill.BackgroundColor = bg;
                rowRange.Style.Border.BottomBorder = XLBorderStyleValues.Thin;
                rowRange.Style.Border.BottomBorderColor = XLColor.FromHtml("#E0E0E0");
                row++;
            }
            else if (r.ChangeType == Domain.Enums.ChangeType.Deleted)
            {
                var isAlt = seq % 2 == 0;
                var bg = isAlt ? AlternateRow : XLColor.White;

                ws.Cell(row, 1).Value = seq++;
                ws.Cell(row, 2).Value = r.FullObjectName;
                ws.Cell(row, 3).Value = "Present in Source";
                ws.Cell(row, 4).Value = "Missing (Procedure not in Target)";
                ws.Cell(row, 5).Value = "Procedure Deleted";
                ws.Cell(row, 6).Value = r.DetectedAt.ToString("yyyy-MM-dd HH:mm");

                var rowRange = ws.Range(row, 1, row, 6);
                rowRange.Style.Fill.BackgroundColor = bg;
                rowRange.Style.Border.BottomBorder = XLBorderStyleValues.Thin;
                rowRange.Style.Border.BottomBorderColor = XLColor.FromHtml("#E0E0E0");
                row++;
            }
            else // Modified
            {
                var paramDiffs = r.Differences.Where(d => d.Contains("Parameter")).ToList();
                if (paramDiffs.Count == 0)
                    continue;

                foreach (var diff in paramDiffs)
                {
                    var isAlt = seq % 2 == 0;
                    var bg = isAlt ? AlternateRow : XLColor.White;
                    var (srcParam, tgtParam, diffText) = ParseParameterDiff(diff);

                    ws.Cell(row, 1).Value = seq++;
                    ws.Cell(row, 2).Value = r.FullObjectName;
                    ws.Cell(row, 3).Value = srcParam;
                    ws.Cell(row, 4).Value = tgtParam;
                    ws.Cell(row, 5).Value = diffText;
                    ws.Cell(row, 6).Value = r.DetectedAt.ToString("yyyy-MM-dd HH:mm");

                    var rowRange = ws.Range(row, 1, row, 6);
                    rowRange.Style.Fill.BackgroundColor = bg;
                    rowRange.Style.Border.BottomBorder = XLBorderStyleValues.Thin;
                    rowRange.Style.Border.BottomBorderColor = XLColor.FromHtml("#E0E0E0");

                    ws.Cell(row, 5).Style.Fill.BackgroundColor = ModifiedBg;
                    ws.Cell(row, 5).Style.Font.FontColor = ModifiedFg;
                    ws.Cell(row, 5).Style.Font.Bold = true;

                    row++;
                }
            }
        }

        if (seq == 1)
        {
            MergeCells(ws, 4, 1, 4, 6);
            ws.Cell(4, 1).Value = "No procedure parameter differences found.";
            ws.Cell(4, 1).Style.Font.Italic = true;
            ws.Cell(4, 1).Style.Alignment.Horizontal = XLAlignmentHorizontalValues.Center;
        }

        ApplyWidths(ws, widths);
        ws.SheetView.FreezeRows(3);
    }

    private static (string SourceParam, string TargetParam, string DiffType) ParseParameterDiff(string diff)
    {
        if (diff.Contains("is missing in Target"))
        {
            var match = System.Text.RegularExpressions.Regex.Match(diff, @"Parameter '([^']+)'");
            var param = match.Success ? match.Groups[1].Value : "Parameter";
            var lineMatch = System.Text.RegularExpressions.Regex.Match(diff, @"on line (\d+)");
            var lineInfo = lineMatch.Success ? $" (Line {lineMatch.Groups[1].Value})" : "";
            return (param + lineInfo, "Missing", "Missing in Target");
        }
        else if (diff.Contains("is missing in Source"))
        {
            var match = System.Text.RegularExpressions.Regex.Match(diff, @"Parameter '([^']+)'");
            var param = match.Success ? match.Groups[1].Value : "Parameter";
            var lineMatch = System.Text.RegularExpressions.Regex.Match(diff, @"on line (\d+)");
            var lineInfo = lineMatch.Success ? $" (Line {lineMatch.Groups[1].Value})" : "";
            return ("Missing", param + lineInfo, "Missing in Source");
        }
        else if (diff.Contains("->"))
        {
            var parts = diff.Split("->");
            var left = parts[0].Trim();
            var right = parts[1].Trim();

            var nameMatch = System.Text.RegularExpressions.Regex.Match(left, @"Parameter \d+ '([^']+)'");
            var paramName = nameMatch.Success ? nameMatch.Groups[1].Value : "";

            if (diff.Contains("Name:"))
            {
                var sourceVal = left.Substring(left.IndexOf("Name:") + 5).Trim();
                return (sourceVal, right, "Name Mismatch");
            }
            else if (diff.Contains("DataType:"))
            {
                var sourceVal = left.Substring(left.IndexOf("DataType:") + 9).Trim();
                return ($"{paramName} ({sourceVal})", $"{paramName} ({right})", "DataType Mismatch");
            }
            else if (diff.Contains("IsOutput:"))
            {
                var sourceVal = left.Substring(left.IndexOf("IsOutput:") + 9).Trim();
                return ($"{paramName} (Output: {sourceVal})", $"{paramName} (Output: {right})", "Output Flag Mismatch");
            }
            else if (diff.Contains("Position:"))
            {
                var sourceVal = left.Substring(left.IndexOf("Position:") + 9).Trim();
                return ($"{paramName} (Pos: {sourceVal})", $"{paramName} (Pos: {right})", "Position Mismatch");
            }
        }

        return ("", "", diff);
    }
}
